server:
  port: 8085

spring:
  application:
    name: cloud-graphql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vehicle?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql

graphql:
  servlet:
    mapping: /graphql
